version: "3.7"

services:
  db-imperium-01:
    image: postgres:alpine
    ports:
      - 5430:5432
    container_name: "imperium-01-db"
    restart: always
    environment:
      - POSTGRES_USER=imperium-user
      - POSTGRES_PASSWORD=imperium-password
      - POSTGRES_DB=mydb
    volumes:
      - database-imperium-01:/var/lib/postgresql/data

volumes:
  database-imperium-01:

  # Preencher os campos
  # Verificar se a porta ja esta sendo utilizada e modificar para outra  ex: 5433:5432
  # docker-compose up -d
