version: "3.7"

services:
  db-[ YOUR DATABASE NAME HERE *** ]:
    image: postgres:alpine
    ports:
      - 5432:5432
    container_name: "[ YOUR CONTAINER NAME HERE ]"
    restart: always
    environment:
      - POSTGRES_USER=[ YOUR USERNAME HERE ]
      - POSTGRES_PASSWORD=[ YOUR PASSWORD HERE ]
      - POSTGRES_DB=mydb
    volumes:
      - database-[ YOUR DATABASE NAME HERE *** ]:/var/lib/postgresql/data

volumes:
  database-[ YOUR DATABASE NAME HERE *** ]:
